version: "3.9"
services:
  fastapi:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./fastapi-app:/app
    command: bash -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - ollama

  qdrant:
    image: qdrant/qdrant:v1.12.4
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  # Alternativa más simple con Ollama
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*

volumes:
  qdrant_storage:
  ollama_data:

